#!/usr/bin/env python3
"""
gen-favicon.py — Generate favicon.svg for a Spatial Deck fork.

Usage:
    python3 tools/gen-favicon.py "Talk Title"
    python3 tools/gen-favicon.py "Talk Title" --accent teal
    python3 tools/gen-favicon.py "Talk Title" --accent "#00d4ff" --bg "#0a1530"
    python3 tools/gen-favicon.py --glyph "AB"             # explicit glyph override

Picks 1–2 letters from the title (uppercase initials, max 2) and renders them
on a dark rounded-rect background with the chosen accent color. Writes
`favicon.svg` to the repo root, overwriting any existing default.

If you want a multi-resolution favicon.ico in addition to the SVG (older
browsers, some bookmark managers), pass --also-ico and have Pillow installed:
    pip3 install pillow
    python3 tools/gen-favicon.py "Talk Title" --also-ico
"""

import argparse
import re
import sys
from pathlib import Path

ACCENT_PRESETS = {
    "teal":   "#00d4ff",
    "amber":  "#f59e0b",
    "rose":   "#f43f5e",
    "purple": "#a78bfa",
}

SVG_TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <!-- Spatial Deck fork favicon — generated by tools/gen-favicon.py
       Title: {title!r} · Glyph: {glyph!r} · Accent: {accent} -->
  <defs>
    <radialGradient id="bg" cx="50%" cy="40%" r="65%">
      <stop offset="0%" stop-color="{bg_top}"/>
      <stop offset="100%" stop-color="{bg_bot}"/>
    </radialGradient>
    <radialGradient id="glow" cx="50%" cy="50%" r="55%">
      <stop offset="0%" stop-color="{accent}" stop-opacity=".35"/>
      <stop offset="60%" stop-color="{accent}" stop-opacity=".08"/>
      <stop offset="100%" stop-color="{accent}" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="64" height="64" rx="14" fill="url(#bg)"/>
  <circle cx="32" cy="32" r="28" fill="url(#glow)"/>
  <text x="32" y="{text_y}" text-anchor="middle"
        font-family="-apple-system, 'Space Grotesk', 'Helvetica Neue', sans-serif"
        font-size="{font_size}" font-weight="700"
        fill="{accent}" letter-spacing="-1">{glyph}</text>
</svg>
"""


def initials_from_title(title: str, max_chars: int = 2) -> str:
    """Pull up to N uppercase initials from a title (first letter of each word)."""
    words = re.findall(r"[A-Za-z0-9]+", title)
    if not words:
        return "SD"
    # Strip leading articles / prepositions / single conjunctions
    stop = {"a", "an", "the", "of", "for", "and", "with", "is", "are", "in", "on"}
    meaty = [w for w in words if w.lower() not in stop] or words
    initials = "".join(w[0] for w in meaty[:max_chars]).upper()
    return initials or "SD"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("title", nargs="?", default=None, help="Talk title (initials picked from this)")
    ap.add_argument("--glyph", default=None, help="Explicit glyph override (1–3 chars)")
    ap.add_argument("--accent", default="teal",
                    help="Accent color name (teal/amber/rose/purple) or hex")
    ap.add_argument("--bg-top", default="#0a1530", help="Top of background gradient")
    ap.add_argument("--bg-bot", default="#03060f", help="Bottom of background gradient")
    ap.add_argument("--out", default="favicon.svg", help="Output path")
    ap.add_argument("--also-ico", action="store_true",
                    help="Also emit favicon.ico (16/32/48) via Pillow (requires pip install pillow)")
    args = ap.parse_args()

    if not args.title and not args.glyph:
        ap.error("Provide either a title or --glyph")

    glyph = args.glyph or initials_from_title(args.title)
    glyph = glyph[:3]  # cap at 3
    accent = ACCENT_PRESETS.get(args.accent, args.accent)

    # Scale font down for longer glyphs so they fit the 64-unit canvas
    sizing = {1: (42, 46), 2: (28, 42), 3: (20, 40)}
    font_size, text_y = sizing.get(len(glyph), (20, 40))

    svg = SVG_TEMPLATE.format(
        title=args.title or "(no title)",
        glyph=glyph,
        accent=accent,
        bg_top=args.bg_top,
        bg_bot=args.bg_bot,
        font_size=font_size,
        text_y=text_y,
    )
    out = Path(args.out)
    out.write_text(svg, encoding="utf-8")
    print(f"Wrote {out} (glyph={glyph!r}, accent={accent})")

    if args.also_ico:
        try:
            from PIL import Image, ImageDraw, ImageFont  # type: ignore
        except ImportError:
            print("warn: --also-ico requested but Pillow not installed; skipping. "
                  "Run `pip3 install pillow` and re-try.", file=sys.stderr)
            return 0
        # Render a 256×256 PNG of the glyph then write multi-res .ico
        ico_path = out.with_suffix(".ico")
        png_path = out.with_suffix(".png")
        size = 256
        img = Image.new("RGBA", (size, size), (10, 21, 48, 255))
        draw = ImageDraw.Draw(img)
        try:
            font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc",
                                      int(size * font_size / 64))
        except OSError:
            font = ImageFont.load_default()
        # rough center
        bbox = draw.textbbox((0, 0), glyph, font=font)
        w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
        draw.text(((size - w) / 2 - bbox[0], (size - h) / 2 - bbox[1]),
                  glyph, font=font,
                  fill=accent if accent.startswith("#") else "#00d4ff")
        img.save(png_path)
        img.save(ico_path, sizes=[(16, 16), (32, 32), (48, 48)])
        print(f"Wrote {png_path} and {ico_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
